# Generated by Django 6.0.4 on 2026-07-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0022_contrarecibo_contrarecibofactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='es_preventivo',
            field=models.BooleanField(default=False, verbose_name='¿Mantenimiento Preventivo?'),
        ),
    ]
