# Generated by Django 6.0.4 on 2026-07-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0023_factura_es_preventivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrarecibo',
            name='es_efectivo',
            field=models.BooleanField(default=False, verbose_name='¿Es pago en efectivo?'),
        ),
    ]
