# Generated by Django 6.0.4 on 2026-07-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0024_contrarecibo_es_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrarecibo',
            name='sin_desglose',
            field=models.BooleanField(default=False, verbose_name='Sin Desglose de Impuestos'),
        ),
    ]
