# Generated by Django 6.0.4 on 2026-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0025_contrarecibo_sin_desglose'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrarecibofactura',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Descuento'),
        ),
    ]
