# Generated by Django 6.0.4 on 2026-07-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfil_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avatar',
            field=models.CharField(blank=True, default='User', max_length=50, null=True, verbose_name='Icono de Avatar'),
        ),
    ]
